title: "Mnémotechniques + répétition – Initiation à la Génomique"
description: "Fiches + répétition espacée (reconnaissance, auditif, visuel par répétition)"
theme: jekyll-theme-minimal
markdown: kramdown
